image: composer

stages:
  - unit-test
  - analysis

unit test:
  stage: unit-test
  before_script:
  - composer update
  - apk add build-base autoconf
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - php -v
  script:
  - composer test
  artifacts:
    paths:
      - reports/phpunit.coverage.xml
      - reports/phpunit.report.xml
    expire_in: 1 week
    reports:
      junit:
      - reports/phpunit.report.xml

sonar:
  stage: analysis
  image: mercuriete/sonar-scanner
  script:
  - sonar-scanner -Dsonar.exclusions=**/*.xml -Dproject.settings=sonar-scanner.properties -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_URL

