image: composer

stages:
  - unit-test
  - analysis

unit test:
  stage: unit-test
  before_script:
  - composer update
  script:
  - composer unittest

sonar:
  stage: analysis
  image: mercuriete/sonar-scanner
  script:
  - sonar-scanner -Dsonar.exclusions=**/*.xml -Dproject.settings=sonar-scanner.properties -Dsonar.login=4c8b8575a0742e5dd83034f24fe552f19a4c4df8 -Dsonar.host.url=http://sonar.sergeylobin.ru:9000"
#   -Dsonar.host.url=$$$SONAR_URL$$$ -Dsonar.projectKey=$$$SONAR_PROJECT_KEY$$$ -Dsonar.projectName=$$$SONAR_PROJECT_KEY$$$ -Dsonar.sources=torpydo,tests,features -Dsonar.python.xunit.reportPath=nosetests.xml -Dsonar.python.coverage.reportPaths=coverage.xml

